import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introdução',
      link: {
        type: 'generated-index',
      },
      items: [
        'intro',
      ],
    },
    {
      type: 'category',
      label: 'Guias',
      link: {
        type: 'generated-index',
      },
      items: [
        'guides/primeiros-passos',
        'guides/xcloud-cli-guia-completo',
        'guides/dominio-customizado',
        'guides/funcoes-serverless',
        {
          type: 'category',
          label: 'Migração',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/migration',
            },
          ],
        },
        {
          type: 'category',
          label: 'Deploy',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/deployment',
            },
          ],
        },
        {
          type: 'category',
          label: 'Testing',
          items: [
            {
              type: 'autogenerated',
              dirName: 'guides/testing',
            },
          ],
        },
        {
          type: 'category',
          label: 'Setup e Configuração',
          items: [
            {
              type: 'autogenerated',
              dirName: 'setup',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Arquitetura',
      link: {
        type: 'generated-index',
      },
      items: [
        'architecture/arquitetura',
        'architecture/estrutura-do-projeto',
        'architecture/arquitetura-de-componentes',
      ],
    },
    {
      type: 'category',
      label: 'Referência da CLI',
      link: {
        type: 'generated-index',
      },
      items: [
        'cli/introduction',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        description: 'Referência completa da API da xCloud Platform',
      },
      items: [
        'api/introduction',
        'api/authentication',
        'api/projects',
        'api/deployments',
        'api/data-models',
      ],
    },
    {
      type: 'category',
      label: 'Referência do Projeto',
      link: {
        type: 'generated-index',
        description: 'Informações sobre o projeto, contributors, changelog e licença',
      },
      items: [
        'reference/changelog',
        'reference/contribuidores',
        'reference/seguranca',
        'reference/licenca',
      ],
    },
  ],
};

export default sidebars;