name: '🚀 Coordinate Docs Automation'

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: 'The issue number to be solved by the AI bot'
        required: true
        type: string

jobs:
  coordinate:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: write

    steps:
      - name: 'Mint identity token'
        id: 'mint_identity_token'
        uses: 'actions/create-github-app-token@v1'
        with:
          app-id: '${{ vars.APP_ID }}'
          private-key: '${{ secrets.APP_PRIVATE_KEY }}'

      - name: 'Acknowledge Issue'
        uses: actions/github-script@v7
        with:
          github-token: '${{ steps.mint_identity_token.outputs.token }}'
          script: |
            const issue_number = ${{ github.event.inputs.issue-number }};
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: '🤖 Understood. I will now begin working on this issue. A pull request will be created shortly.'
            });

      - name: 'Trigger Issue Solver Workflow'
        uses: actions/github-script@v7
        with:
          github-token: '${{ steps.mint_identity_token.outputs.token }}'
          script: |
            const issue_number = ${{ github.event.inputs.issue-number }};
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'solve-docs-issue.yml',
              ref: 'main',
              inputs: {
                'issue-number': issue_number
              },
            });
            console.log(`Successfully triggered the solver workflow for issue #${issue_number}.`);
