name: '🤖 Handoff to Copilot Agent'

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  assign_to_copilot:
    # Apenas executa se o título da issue começar com [HANDOFF]
    if: startsWith(github.event.issue.title, '[HANDOFF]')
    runs-on: ubuntu-latest

    steps:
      - name: 'Assign issue to GitHub Copilot'
        uses: actions/github-script@v7
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            console.log(`Assigning issue #${issueNumber} to the Copilot agent.`);

            try {
              await github.rest.issues.addAssignees({
                owner,
                repo,
                issue_number: issueNumber,
                assignees: ['copilot']
              });

              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issueNumber,
                body: '🤖 Tarefa recebida. O agente GitHub Copilot começará a trabalhar nesta issue em breve.'
              });

            } catch (error) {
              console.error(`Failed to assign Copilot to issue #${issueNumber}:`, error);
              
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: issueNumber,
                body: `🤖 Falha ao tentar atribuir esta tarefa ao agente Copilot. Verifique se o app 'GitHub Copilot' tem as permissões necessárias neste repositório. Erro: ${error.message}`
              });
            }
